repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-executables-have-shebangs
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.17
  hooks:
  - id: shellcheck
