apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  source:
    path: apps/grafana
    repoURL: https://github.com/lucas-giaco/argocd-local.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - "values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  project: default
