apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- ingress.yaml

# Base apps
- ../../../apps/argocd
- ../../../apps/ingress-nginx/overlays/local
- ../../../apps/metrics-server/overlays/local
