apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newName: argoproj/argocd
    newTag: v2.1.7
  - name: ghcr.io/dexidp/dex
    newTag: v2.30.0
  - name: argoprojlabs/argocd-notifications
    newTag: v1.2.0
  - name: redis
    newTag: 6.2.4-alpine

resources:
- ../../base
- ingress.yaml

# Base apps
- ../../../apps/argocd
- ../../../apps/ingress-nginx/overlays/local
# Metrics scraping
- ../../../apps/metrics-server/overlays/local
- ../../../apps/prometheus-adapter/overlays/local
# Monitoring
- ../../../apps/grafana/overlays/local
- ../../../apps/prometheus/overlays/local
# Logging
- ../../../apps/loki/overlays/local
# Security
- ../../../apps/kube-bench
# Infra provisioning
- ../../../apps/crossplane

# These apps aren't needed for a local env but I
# want to add them to test the deployment process
- ../../../apps/cert-manager
- ../../../apps/external-dns
- ../../../apps/cluster-autoscaler
