apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- ingress.yaml

# Base apps
- ../../../apps/argocd
- ../../../apps/ingress-nginx/overlays/local
# Monitoring
- ../../../apps/metrics-server/overlays/local
- ../../../apps/prometheus/overlays/local

# The apps aren't needed for a local env but I
# want to add the to test the deployment process
- ../../../apps/cert-manager
- ../../../apps/external-dns
