apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  source:
    path: apps/metrics-server
    repoURL: https://github.com/lucas-giaco/argocd-local.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - "values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
  project: default
