apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- role-binding.yaml
- service-account.yaml
- service.yaml

vars:
- name: ARGOCD_REDIS_SERVICE
  objref:
    kind: Service
    name: argocd-redis
    apiVersion: v1
