apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.10.0

resources:
  - deployment.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
