apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  source:
    path: apps/crossplane
    repoURL: https://github.com/lucas-giaco/argocd-local.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - "values.yaml"
  # Ignore diffs in cluster role rules as they are managed by crossplane rbac-manager
  ignoreDifferences:
    - kind: ClusterRole
      name: crossplane
      namespace: crossplane-system
      jsonPointers:
        - /rules
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  project: default
