apiVersion: v2
name: cluster-autoscaler
description: Scales Kubernetes worker nodes within autoscaling groups.
type: application

version: 0.1.0
appVersion: 1.21.1

dependencies:
  - name: cluster-autoscaler
    repository: https://kubernetes.github.io/autoscaler
    version: 9.10.8
