apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- role.yaml
- role-binding.yaml
- service-account.yaml
- service.yaml
- metrics-service.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
