apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-bench
spec:
  source:
    path: apps/kube-bench
    repoURL: https://github.com/lucas-giaco/argocd-local.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  project: default
