apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  source:
    path: apps/loki
    repoURL: https://github.com/lucas-giaco/argocd-local.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - "values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  project: default
