apiVersion: v1
kind: Secret
metadata:
  name: loki-datasource
  namespace: logging
  labels:
    grafana_datasource: "true"
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logging:3100
      editable: false
      isDefault: true
